/*
 * This class is based on main-packet-tag.cc example with slight modifications:
 * - a uint32_t tag that is added to all packets generated by FtOnOffApplication
 * - used in routing to route by flowId
 */

#ifndef FT_TAG
#define FT_TAG

#include "ns3/tag.h"
#include "ns3/packet.h"
#include "ns3/uinteger.h"
#include <iostream>
 
namespace ns3 {

class FtTag : public Tag
{
public:
  static TypeId GetTypeId (void);
  virtual TypeId GetInstanceTypeId (void) const;
  virtual uint32_t GetSerializedSize (void) const;
  virtual void Serialize (TagBuffer i) const;
  virtual void Deserialize (TagBuffer i);
  virtual void Print (std::ostream &os) const;

  // these are our accessors to our tag structure
  void SetSimpleValue (uint32_t value);
  uint32_t GetSimpleValue (void) const;
private:
  uint32_t m_simpleValue;  
};

} // namespace ns3

#endif /* FT_TAG */
