# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ft-internet', ['internet'])
    module.source = [
        'model/ft-ipv4-static-routing.cc',
        'model/ft-ipv4-routing-table-entry.cc',
        'model/ft-tag.cc',
        'model/ft-onoff-application.cc',
        'helper/ft-ipv4-static-routing-helper.cc',
        'helper/ft-on-off-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ft-internet')
    module_test.source = [
        'test/ft-internet-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ft-internet'
    headers.source = [
        'model/ft-ipv4-static-routing.h',
        'model/ft-ipv4-routing-table-entry.h',
        'model/ft-tag.h',
        'model/ft-onoff-application.h',
        'helper/ft-ipv4-static-routing-helper.h',
        'helper/ft-on-off-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

